services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./ecommerce.mongodb.js:/docker-entrypoint-initdb.d/ecommerce.mongodb.js
    environment:
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: admin123
      # MONGO_INITDB_DATABASE: ecommerce

volumes:
  mongo_data:
    # driver: local